### ISSUE TITLE
Make home page like gradient to other pages also

### ISSUE THREAD

**Issue by Namanbhatia7** [Namanbhatia7/False9#17]
Make gradient used in home page to other pages with same concept and different colors

**Comment by subhashissuara** [comment]
@Namanbhatia7 I would like to work on it.

**Comment by Namanbhatia7** [comment]
I have assigned it to you. 
Looking forward to your PR

**Comment by subhashissuara** [comment]
Thank you, are there any color preferences I should keep in mind?

**Comment by Namanbhatia7** [comment]
![1179-Khel-Now-9](https://user-images.githubusercontent.com/52316491/94862174-3a7e8200-0456-11eb-95b9-b162504f64a8.jpg)
You can take colors from the stripes as reference
Ensure that gradient looks aesthetic and not too bright.

**Comment by subhashissuara** [comment]
Okay, gotcha!

**Comment by priyankaagrawal123** [comment]
I am interested. I can implement.
Please assign this issue to me.

**Comment by subhashissuara** [comment]
@Namanbhatia7 I am adding 2 pages for review:

![image](https://user-images.githubusercontent.com/28859415/94914225-3d19bf80-04c8-11eb-80a0-71a13b957703.png)

![image](https://user-images.githubusercontent.com/28859415/94914490-c16c4280-04c8-11eb-8e24-d8a5e7f5eea0.png)

The teams page has green from body background property behind scrollbar which shows up only while taking full page screenshot (I had to wrap everything in a div and do position absolute as it wasn't allowing me to cover the gradient for the whole page). Here it is without full page screenshot:

![image](https://user-images.githubusercontent.com/28859415/94915953-6556ed80-04cb-11eb-98de-363b540cc849.png)


I wanted to ask if I should do anything about the scorers page. This is the current view:

![image](https://user-images.githubusercontent.com/28859415/94914720-2b84e780-04c9-11eb-86dd-70141b5cb7bb.png)

Since, there is no gradient for standing table so, I am assuming this shouldn't have too?
Lemme know if any changes or additions are required.
